### ISSUE TITLE
Problem mit ACPOptionInstruction

### ISSUE THREAD

**Issue by nils-kt** [manuth/WoltLabCompiler#227]
Hallo, sobald ich ACPOptionInstruction hinzufügen möchte, erhalte ich bei der Installation folgenden Fehler: 

> Die Installations-Anweisungen geben für das Package Installation Plugin „option“ die Datei „components/option/*“ an, diese ist jedoch nicht im Archiv enthalten. Mögliche Ursachen:

Mein Test Code:
```ts
import { ACPOptionInstruction, OptionType } from "@manuth/woltlab-compiler";

/**
 * The instruction.
 */
export let MyACPOptionInstruction = new ACPOptionInstruction(
    {
        FileName: "acpOptions.xml",
        Nodes: [
            {
                Name: "test",
                Item: {
                    DisplayName: {
                        de: "Test Plugin",
                        en: "Test Plugin"
                    },
                    Options: [
                        {
                            Name: "enabled",
                            DisplayName: {
                                de: "Aktiviert",
                                en: "Enabled"
                            },
                            Description: {
                                de: "Aktiviert das Test Plugin",
                                en: "Enables the Test Plugin"
                            },
                            Type: OptionType.CheckBox
                        }
                    ]
                }
            }
        ]
    });
```

**Comment by nils-kt** [comment]
Hi, nach dem Update schlägt die Installation mit einem Error fehl:

```
Error Type:

wcf\system\exception\SystemException

Error Message:

Cannot determine language code of language file 'components/translations/'

File:

*/lib/system/package/plugin/LanguagePackageInstallationPlugin.class.php (92)
```

Fehlerhaft generierte Instructions:
```xml
<instruction type="language">components/translations/*</instruction>
<instruction type="language">components/option/*</instruction>
```

**Comment by manuth** [comment]
Hallo @nils-kt 
An erster Stelle vielen Dank dafür, dass du mein Projekt nutzt - ich bin echt happy darüber, zu sehen, dass es zur Abwechslung von jemand anderem als mir selbst genutzt wird 😂 
Leider kann ich den Fehler nicht reproduzieren - bei mir funktioniert die neue Version.

Kannst du das resultierende `.tar`-Paket hochladen?

**Comment by nils-kt** [comment]
Hi, 
das Projekt ist echt cool und nimmt viel Arbeit ab.
Ich schicke dir den Source und das Archiv an deine E-Mail Adresse.

**Comment by manuth** [comment]
Die Mail ist leider noch nicht angekommen.

Werde mich aber so schnell wie möglich darum kümmern, sobald ich diese erhalten habe. ^^

**Comment by nils-kt** [comment]
Ist sie mittlerweile angekommen? Hab sie an m@... gesendet.

**Comment by manuth** [comment]
Hab sie leider weder im Posteingang noch im Spam-Ordner erhalten.
Kann leider nicht sagen, woran es liegen könnte.

Alternativ kannst du das Archiv als Anhang in den Kommentar posten.
Sollte dir das unangenehm sein, kannst du die Files gerne auf meiner Cloud hochladen:
https://cloud.nuth.ch/s/kKKPyKHMNZpy6tr

**Comment by nils-kt** [comment]
Hab dir die test.zip hochgeladen.

**Comment by manuth** [comment]
Vielen Dank - konnte den Fehler jetzt nachstellen. Musste aber zuerst meine WoltLab Suite Core Version aktualisieren.
Wenn ich alles richtig verstehe, dürfte es nicht allzu viele Änderungen benötigen, um das zu beheben.

Sorry für die Umstände und danke für die Geduld! ✨

**Comment by manuth** [comment]
So - das sollte das Problem rein theoretisch lösen
Du kannst das Ticket gern wieder auf machen, falls das Problem weiterhin bestehen sollte.

Freut mich sehr, dass ich helfen konnte 😄
