### ISSUE TITLE
Add a Documentation (and more examples)

### ISSUE THREAD

**Issue by nils-kt** [manuth/WoltLabCompiler#229]
_I'll create the issue in English so that everyone can understand it._
_This is not really an issue, but rather a suggestion for improvement. But as there are no further contact options, I'll take this step._

It would be useful to provide a documentation and more examples to get you started. Especially at the beginning it is quite difficult to work with WoltLabCompiler, because currently no documentation is available and you have to orientate yourself by the two existing examples and the comments in the code.

If there was a documentation and maybe more examples, I'm sure more people would support and use this project.

**Comment by manuth** [comment]
Sadly, I'm not that good of a doc writer but I did the best I could.
I'll gladly accept a PR improving the docs.

Once they're pushed to this repo, please let me know what you think of the new docs.

Thanks for your intereset in this project!
This is most appreciated ✨
